try{
 let x=0;
 val = x/0
 console.log(val);
}
catch(err){
    console.log(err)
}
