try{
    console.logg("hello")
}
catch(err){
    console.log("it didnt go ")
}
